dinit(700,700)
bi = bits.readnew("image.png")
hit = BitImage:new()
miss = BitImage:new()
bits.parse_hitmiss(hit,miss,"-...+...-\n-...+...-")
bits.dshow(hit,"a")
bits.dshow(miss,"b")
bits.dshow(bi,"c")
bits.mask_hitmiss(bi,hit,miss)
bits.dshow(bi,"d")
dwait()
